# Generated by Django 4.0.5 on 2022-06-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_allergy_allergy_drink_allergy_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='category',
            new_name='drink',
        ),
    ]
