# Generated by Django 4.0.5 on 2022-06-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_allergy_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
